SGF/Models/Presupuesto.cs
using NPOI.SS.Formula.Functions;
using System.ComponentModel.DataAnnotations;

namespace SGF.Models
{
    public class Presupuesto
    {
        [Key]
        public long Id { get; set; }
        public string Cliente { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public double Monto { get; set; }
        public double? Esigef { get; set; }
        public double? EnEsigef { get; set; } 

    }
}

SGF/Controllers/PresupuestoController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SGF.Context;
using SGF.Models;

namespace SGF.Controllers
{
    public class PresupuestoController : Controller
    {
        private readonly AppDbContext _context;
        public PresupuestoController(AppDbContext context)
        {
            _context = context;
        }
        // GET: PresupuestoController1
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult ShowData([FromForm] IFormFile FileExcel)
        {
            /*if (FileExcel.Length==0)
            {
                return BadRequest("No existe archivo");
            }*/
            var workbook = new XLWorkbook(FileExcel.OpenReadStream());
            var sheet = workbook.Worksheet(1);
            var sheetName = sheet.Name;

            var firstRowUsed = sheet.FirstRowUsed().RangeAddress.FirstAddress.RowNumber;
            var lastRowUsed = sheet.LastRowUsed().RangeAddress.FirstAddress.RowNumber;

            var contacts = new List<Presupuesto>();

            for (int i = firstRowUsed + 1; i <= lastRowUsed; i++)
            {
                var row = sheet.Row(i);
                contacts.Add(new Presupuesto
                {
                    Cliente = row.Cell(1).GetString(),
                    Anio = 2023, //row.Cell(2).GetString(),
                    Mes = 9, //row.Cell(3).GetString(),
                    Monto = row.Cell(3).GetDouble(), //row.Cell(4).GetString()
                });

            }
            Console.WriteLine(FileExcel);
            return StatusCode(StatusCodes.Status200OK, contacts);
        }

        [HttpPost]
        public IActionResult SaveData([FromForm] IFormFile FileExcel)
        {
            if (FileExcel == null)
            {
                return BadRequest("No existe archivo");
            }
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    var workbook = new XLWorkbook(FileExcel.OpenReadStream());
                    var sheet = workbook.Worksheet(1);

                    var firstRowUsed = sheet.FirstRowUsed().RangeAddress.FirstAddress.RowNumber;
                    var lastRowUsed = sheet.LastRowUsed().RangeAddress.FirstAddress.RowNumber;

                    var contacts = new List<Presupuesto>();

                    for (int i = firstRowUsed + 1; i <= lastRowUsed; i++)
                    {
                        var row = sheet.Row(i);
                        Presupuesto contact = new Presupuesto
                        {
                            Cliente = row.Cell(1).GetString(),
                            Anio = 2023,
                            Mes = 9,
                            Monto = row.Cell(3).GetDouble(),
                        };
                        contacts.Add(contact);
                    }
                    _context.AddRange(contacts);
                    _context.SaveChanges();
                    transaction.Commit();
                    Console.WriteLine(FileExcel);
                    return StatusCode(StatusCodes.Status200OK, new { mensaje = "Ok" });
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    return Json(new { mensaje = ex.Message });
                }
            }
        }

    }
}

SGF/Views/Presupuesto/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-header">

                <span class="d-inline align-items-end">Cargar Excel<a class="btn btn-info" asp-action="ExportarData">Reporte Excel</a></span>
            </div>
            <div class="card-body">

                <div class="row">
                    <div class="col-sm-4">
                        <form id="form" enctype="multipart/form-data">
                            <input class="form-control-file" type="file" id="inputExcel" name="FileExcel" />
                        </form>
                    </div>
                    <div class="col-sm-4">
                        <button class="btn btn-warning show-file" onclick="mostrarDatos()">Mostrar Datos</button>
                        <button class="btn btn-success save-file" onclick="enviarDatos()">Enviar Datos a BD</button>
                    </div>
                </div>

                <hr />

                <div class="row">
                    <div class="col-sm-12">
                        <table id="tbData" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Anio</th>
                                    <th>Mes</th>
                                    <th>Monto</th>
                                    <th>Esigef</th>
                                    <th>EnEsigef</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        const cargando = `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                  <b>Cargando...</b>`;

        function mostrarDatos() {
            const url = "@Url.Action("ShowData", "Presupuesto")/";
            //const url = "@Url.Action("GenerateExcel", "Presupuesto")/";
            const formData = new FormData($("#form")[0]);

            $.ajax({
                url: url,
                data: formData,
                method: 'POST',
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
                beforeSend: function () {
                    $('.show-file').html(cargando);
                }
            })
                ///.then((response) => { return response.json() })
                .done((dataJson) => {
                    console.log(dataJson);
                    $('.show-file').html('Mostrar Datos');
                    dataJson.forEach((item) => {
                        $("#tbData tbody").append(
                            $("<tr>").append(
                                $("<td>").text(item.cliente),
                                $("<td>").text(item.anio),
                                $("<td>").text(item.mes),
                                $("<td>").text(item.monto),
                                $("<td>").text(item.esigef),
                                $("<td>").text(item.enesigef)
                            )

                        )
                    })

                })
                .fail((error) => {
                    $('.show-file').html('Mostrar Datos');
                    console.error(error);
                })

        }
        function enviarDatos() {
            const url = "@Url.Action("SaveData", "Presupuesto")/";
            const formData = new FormData($("#form")[0]);

            $.ajax({
                url: url,
                data: formData,
                method: 'POST',
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
                beforeSend: function () {
                    $('.save-file').html(cargando);
                }
            })
                ///.then((response) => { return response.json() })
                .done((dataJson) => {
                    console.log(dataJson);
                    $('.save-file').html('Enviar Datos a BD');

                })
                .fail((error) => {
                    $('.save-file').html('Enviar Datos a BD');
                    console.error(error);
                })

        }
    </script>
}